site_name: RPCT_Toolkit
repo_url: https://github.com/KingoftheNight/RPCT/
repo_name: GitHub
site_description: RAAC-PSSM PROTEIN PREDICTION TOOLKIT
site_author: Liang YC
site_favicon: /img/Logo.ico
copyright: Copyright 2021 By Zuo Lab ,College of life sciences， Inner Mongolia University, Hohhot, 010021, China
page:
  - [index.md, Introduction]
  - [default.md, Default Value]
  - [method.md, Method]
  - [about.md, About]
  - [function.md, Function]
  - [installation.md, Installation]
  - [preparation.md, Preparation]
  - [sample.md, Sample]
theme: readthedocs
